# Generated by Django 3.2.16 on 2023-01-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_revision', models.DateTimeField(blank=True, null=True, verbose_name='Редакция тестирования')),
                ('stage', models.PositiveIntegerField(default=1, verbose_name='Этап')),
                ('answers_quantity', models.PositiveIntegerField(default=0, verbose_name='Ответов')),
                ('started', models.DateTimeField(null=True, verbose_name='Дата начала')),
                ('finished', models.DateTimeField(null=True, verbose_name='Дата завершения')),
                ('passed', models.BooleanField(null=True, verbose_name='Зачтено')),
                ('guest_key', models.CharField(blank=True, editable=False, max_length=36, null=True, verbose_name='Гостевой ключ')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='exams.exam', verbose_name='Тестирование')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(null=True, verbose_name='Результат')),
                ('no_answers', models.BooleanField(null=True, verbose_name='Без ответов')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.progress', verbose_name='Прогресс')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='exams.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_text', models.TextField(null=True, verbose_name='Вариант ответа')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбран пользователем')),
                ('correct', models.BooleanField(default=False, verbose_name='Ответ верен')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='progress.useranswer', verbose_name='Ответ')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='exams.variant', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа пользователя',
                'verbose_name_plural': 'Варианты ответов пользователей',
                'ordering': ['-correct', '-selected'],
            },
        ),
    ]
