# Generated by Django 3.2.16 on 2023-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='guest_key',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Гостевой ключ'),
        ),
    ]
