# Generated by Django 3.2.16 on 2023-01-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='exam_title',
        ),
    ]
