# Generated by Django 3.2.16 on 2023-01-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20230114_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprint',
            name='completed',
        ),
    ]
