# Generated by Django 3.2.16 on 2023-01-05 13:32

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('show_empty', models.BooleanField(default=True, verbose_name='Отображать если нет тестов')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1, editable=False, help_text='Меняется автоматически при изменении/удалении вопросов и вариантов ответов, если тест готов к публикации и не скрыт', verbose_name='Редакция')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('success_message', models.TextField(blank=True, help_text='Не обязательно к заполнению', null=True, verbose_name='Сообщение после прохождения теста')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('change_revision', models.BooleanField(default=False, verbose_name='Менять версию редакции при сохранении теста, вопросов или вариантов ответов')),
                ('timer', models.PositiveIntegerField(blank=True, help_text='Необязательное поле', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='Время на выполнение (мин.)')),
                ('show_results', models.BooleanField(default=True, verbose_name='Отображать пользователю результат после каждого ответа и по окончанию тестирования')),
                ('shuffle_variants', models.BooleanField(default=True, verbose_name='Перемешивать варианты ответов, игнорируя приоритет')),
                ('empty_answers', models.BooleanField(default=False, help_text='Только для типов вопросов с несколькими вариантами ответов', verbose_name='Разрешить оставлять выбор пустым')),
                ('active', models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один не скрытый/готовый к публикации вопрос', verbose_name='Готов к публикации')),
                ('visibility', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Тестирование',
                'verbose_name_plural': 'Тестирования',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Вопрос')),
                ('success_message', models.TextField(blank=True, help_text='Не обязательно к заполнению, выводится в том случае, если опция отображения результата активна', null=True, verbose_name='Сообщение после ответа')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
                ('type', models.CharField(choices=[('one_correct', 'Допустим только один правильный ответ'), ('many_correct', 'Допустимы несколько вариантов ответов')], default='many_correct', max_length=32, verbose_name='Тип')),
                ('active', models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один вариант ответа, соответствующий настройками вопроса и теста', verbose_name='Готов к публикации')),
                ('visibility', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Тестирование')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-visibility', '-active', 'priority', 'id', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст варианта ответа')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
                ('correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='exams.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['priority', 'id', 'text'],
            },
        ),
    ]
