# Generated by Django 3.2.16 on 2023-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_retesting',
            field=models.BooleanField(default=True, verbose_name='Разрешить повторное прохождение'),
        ),
    ]
