# Generated by Django 3.2.16 on 2023-01-11 13:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
