# Generated by Django 3.2.16 on 2023-01-14 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20230114_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
