# Generated by Django 3.2.16 on 2023-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_allow_retesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Краткое описание'),
        ),
    ]
