# Generated by Django 3.2.16 on 2023-01-11 13:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Подробное описание/информация'),
        ),
    ]
