# Generated by Django 3.2.16 on 2023-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_sprint_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='sprint',
        ),
        migrations.AddField(
            model_name='exam',
            name='sprint',
            field=models.ManyToManyField(related_name='exams', to='exams.Sprint', verbose_name='Спринт'),
        ),
    ]
