# Generated by Django 3.2.16 on 2023-01-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20230114_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='sprint',
        ),
        migrations.AddField(
            model_name='exam',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.sprint', verbose_name='Спринт'),
        ),
    ]
