# Generated by Django 3.2.16 on 2023-01-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_question_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created'], 'verbose_name': 'Тесты', 'verbose_name_plural': 'Тест'},
        ),
    ]
