# Generated by Django 3.2.16 on 2023-01-07 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='required_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Необязательное поле. По умолчанию прохождение будет успешным при любом проценте', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Процент верных ответов для успешного прохождения'),
        ),
    ]
