# Generated by Django 3.2.16 on 2023-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_correct',
            field=models.BooleanField(default=True, help_text='Только если активен параметр с отображением пользователю результатов', verbose_name='Подсвечивать верные варианты ответов'),
        ),
    ]
