# Generated by Django 3.2.16 on 2023-01-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20230114_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.sprint', verbose_name='Спринт'),
        ),
    ]
