# Generated by Django 3.2.16 on 2023-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_required_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one_correct', 'Допустим только один правильный ответ'), ('many_correct', 'Допустимы несколько вариантов ответов'), ('text_answer', 'Текстовый ответ')], default='one_correct', max_length=32, verbose_name='Тип'),
        ),
    ]
