# Generated by Django 3.2.16 on 2023-01-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['-created'], 'verbose_name': 'Спринт', 'verbose_name_plural': 'Спринты'},
        ),
    ]
