# Generated by Django 3.2.16 on 2023-01-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_exam_show_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
