# Generated by Django 3.2.16 on 2023-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_sprint_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='description',
        ),
        migrations.AddField(
            model_name='sprint',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Краткое описание'),
        ),
    ]
