# Generated by Django 3.2.16 on 2023-01-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20230119_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='about',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='Краткое описание'),
        ),
    ]
