# Generated by Django 3.2.16 on 2023-01-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_sprint_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='about',
            new_name='description',
        ),
    ]
