# Generated by Django 3.2.16 on 2023-01-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_sprint_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='active',
        ),
        migrations.AddField(
            model_name='sprint',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
