# Generated by Django 3.2.16 on 2023-01-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20230119_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='visibility',
        ),
    ]
