# Generated by Django 3.2.16 on 2023-01-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_remove_sprint_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='only_guest_keys',
            field=models.BooleanField(default=False, verbose_name='Доступ гостям к результатам только по ссылке-приглашению'),
        ),
    ]
