# Generated by Django 3.2.16 on 2023-01-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_finished_sprints',
            field=models.BooleanField(default=False, verbose_name='Скрывать пройденные спринты'),
        ),
    ]
