# Generated by Django 3.2.16 on 2023-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_finished_exams',
            field=models.BooleanField(default=True, verbose_name='Отображать пользователю пройденные тесты'),
        ),
    ]
