# Generated by Django 3.2.16 on 2023-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_show_finished_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_finished_exams',
            field=models.BooleanField(default=False, verbose_name='Скрывать пройденные тесты'),
        ),
    ]
