# Generated by Django 3.2.16 on 2023-01-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_show_finished_exams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='show_finished_exams',
            new_name='hide_finished_exams',
        ),
    ]
