# Generated by Django 3.2.16 on 2022-12-27 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0, editable=False, help_text='Меняется автоматически при изменении/удалении вопросов и вариантов ответов, если тест готов к публикации и не скрыт', verbose_name='Редакция')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('show_results', models.BooleanField(default=True, verbose_name='Отображать результат после каждого ответа')),
                ('shuffle_variants', models.BooleanField(default=True, verbose_name='Перемешивать варианты ответов, игнорируя приоритет')),
                ('empty_answers', models.BooleanField(default=False, help_text='Только для типов вопросов с несколькими вариантами ответов', verbose_name='Разрешить оставлять выбор пустым')),
                ('active', models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один не скрытый/готовый к публикации вопрос', verbose_name='Готов к публикации')),
                ('visibility', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Тестирование',
                'verbose_name_plural': 'Тестирования',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField(default=1, verbose_name='Этап')),
                ('answers', models.PositiveIntegerField(default=0, verbose_name='Ответов')),
                ('started', models.DateTimeField(null=True, verbose_name='Дата начала')),
                ('passed', models.DateTimeField(null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
                ('type', models.CharField(choices=[('one_correct', 'Допустим только один правильный ответ'), ('many_correct', 'Допустимы несколько вариантов ответов')], default='many_correct', max_length=32, verbose_name='Тип')),
                ('active', models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один вариант ответа', verbose_name='Готов к публикации')),
                ('visibility', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-visibility', '-active', 'priority', 'id', 'text'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_revision', models.PositiveIntegerField(null=True, verbose_name='Редакция тестирования')),
                ('exam_title', models.CharField(max_length=200, null=True, verbose_name='Заголовок тестирования')),
                ('question_text', models.TextField(null=True, verbose_name='Текст вопроса')),
                ('correct', models.BooleanField(null=True, verbose_name='Результат')),
                ('no_answers', models.BooleanField(null=True, verbose_name='Без ответов')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.exam', verbose_name='Тестирование')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст варианта ответа')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
                ('correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['priority', 'id', 'text'],
            },
        ),
        migrations.CreateModel(
            name='UserVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_text', models.TextField(null=True, verbose_name='Вариант ответа')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбран пользователем')),
                ('correct', models.BooleanField(default=False, verbose_name='Ответ верен')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questions.useranswer', verbose_name='Ответ')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='questions.variant', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа пользователя',
                'verbose_name_plural': 'Варианты ответов пользователей',
                'ordering': ['-correct', '-selected'],
            },
        ),
    ]
