# Generated by Django 3.2.16 on 2022-12-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='success_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение после прохождения теста'),
        ),
        migrations.AddField(
            model_name='question',
            name='success_message',
            field=models.TextField(blank=True, help_text='Не обязательно к заполнению, выводится в том случае, если опция отображения результата активна', null=True, verbose_name='Сообщение после ответа'),
        ),
    ]
