# Generated by Django 3.2.16 on 2023-01-01 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_useranswer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_empty',
            field=models.BooleanField(default=True, verbose_name='Отображать если нет тестов'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет'),
        ),
    ]
