# Generated by Django 3.2.16 on 2023-01-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20230101_2112'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='exam',
            index_together=set(),
        ),
    ]
