# Generated by Django 3.2.16 on 2023-01-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_exam_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='progress',
            index_together=set(),
        ),
    ]
