# Generated by Django 3.2.16 on 2023-01-05 08:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_progress_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Вопрос'),
        ),
    ]
