# Generated by Django 3.2.16 on 2023-01-05 08:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20230105_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос'),
        ),
    ]
