# Generated by Django 3.2.16 on 2023-01-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20230105_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='change_revision',
            field=models.BooleanField(default=False, verbose_name='Менять версию редакции при сохранении теста, вопросов или вариантов ответов'),
        ),
    ]
