# Generated by Django 3.2.16 on 2022-12-08 23:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['priority', 'text'],
            },
        ),
        migrations.CreateModel(
            name='QuizTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Тематика квизов',
                'verbose_name_plural': 'Тематики квизов',
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст варианта ответа')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
                ('correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['priority', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('show_results', models.BooleanField(default=True, verbose_name='Отображать пользователю подробные результаты')),
                ('shuffle_variants', models.BooleanField(default=True, verbose_name='Перемешивать варианты ответов, игнорируя приоритет')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='questions.quiztheme', verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.quiz', verbose_name='Квиз'),
        ),
    ]
