# Generated by Django 3.2.16 on 2022-12-15 03:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
                ('type', models.CharField(choices=[('one_correct', 'Допустим только один правильный ответ'), ('many_correct', 'Допустимы несколько вариантов ответов'), ('only_text', 'Только текст, без ответов')], default='many_correct', max_length=32, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['priority', 'id', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1, editable=False, help_text='Меняется автоматически при изменении/удалении вопросов и вариантов ответов', verbose_name='Редакция квиза')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('show_results', models.BooleanField(default=True, verbose_name='Отображать пользователю подробные результаты')),
                ('shuffle_variants', models.BooleanField(default=True, verbose_name='Перемешивать варианты ответов, игнорируя приоритет')),
                ('empty_answers', models.BooleanField(default=False, verbose_name='Разрешить оставлять выбор пустым')),
                ('allow_skipping', models.BooleanField(default=False, verbose_name='Разрешить пропуск вопросов')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuizTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=340, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Тематика квизов',
                'verbose_name_plural': 'Тематики квизов',
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_revision', models.PositiveIntegerField(null=True, verbose_name='Редакция квиза')),
                ('quiz_title', models.CharField(max_length=200, null=True, verbose_name='Заголовок квиза')),
                ('question_text', models.TextField(null=True, verbose_name='Текст вопроса')),
                ('correct', models.BooleanField(null=True, verbose_name='Результат')),
                ('skipped', models.BooleanField(null=True, verbose_name='Пропущено')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='questions.question', verbose_name='Вопрос')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.quiz', verbose_name='Квиз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст варианта ответа')),
                ('priority', models.PositiveIntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Приоритет')),
                ('correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['priority', 'id', 'text'],
            },
        ),
        migrations.CreateModel(
            name='UserVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_text', models.TextField(null=True, verbose_name='Вариант ответа')),
                ('correct', models.BooleanField(verbose_name='Результат')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questions.useranswer', verbose_name='Ответ')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='questions.variant', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа пользователя',
                'verbose_name_plural': 'Варианты ответов пользователей',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='questions.quiztheme', verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.quiz', verbose_name='Квиз'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveIntegerField(default=1, verbose_name='Этап')),
                ('answers', models.PositiveIntegerField(default=0, verbose_name='Ответов')),
                ('passed', models.DateTimeField(null=True, verbose_name='Дата завершения')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='questions.quiz', verbose_name='Квиз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
            },
        ),
    ]
