# Generated by Django 3.2.16 on 2022-12-08 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(verbose_name='Результат')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.variant', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Тематика квизов',
                'verbose_name_plural': 'Тематики квизов',
                'ordering': ['-date'],
            },
        ),
    ]
