# Generated by Django 3.2.16 on 2022-12-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_useranswer_no_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='skipped',
            field=models.BooleanField(default=False, verbose_name='Пропущено'),
        ),
    ]
