# Generated by Django 3.2.16 on 2022-12-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_useranswer_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allow_skipping',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='skipped',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one_correct', 'Допустим только один правильный ответ'), ('many_correct', 'Допустимы несколько вариантов ответов')], default='many_correct', max_length=32, verbose_name='Тип'),
        ),
    ]
