# Generated by Django 3.2.16 on 2022-12-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_skipping',
            field=models.BooleanField(default=False, verbose_name='Разрешить пропуск вопросов'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='empty_answers',
            field=models.BooleanField(default=False, verbose_name='Разрешить оставлять выбор пустым'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='stage',
            field=models.PositiveIntegerField(default=1, verbose_name='Этап'),
        ),
    ]
