# Generated by Django 3.2.16 on 2022-12-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20221210_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one_correct', 'Допустим только один правильный ответ'), ('many_correct', 'Допустимы есколько вариантов ответов'), ('only_text', 'Только текст, без ответов')], default='many_correct', max_length=32, verbose_name='Тип'),
        ),
    ]
