# Generated by Django 3.2.16 on 2022-12-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_quiz_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariant',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='Выбран пользователем'),
        ),
        migrations.AlterField(
            model_name='uservariant',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Ответ верен'),
        ),
    ]
