# Generated by Django 3.2.16 on 2022-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one_correct', 'Допустим только один правильный ответ'), ('many_correct', 'Допустимы несколько вариантов ответов'), ('only_text', 'Только текст, без ответов')], default='many_correct', max_length=32, verbose_name='Тип'),
        ),
    ]
