# Generated by Django 3.2.16 on 2022-12-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_uservariant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='started',
            field=models.DateTimeField(null=True, verbose_name='Дата начала'),
        ),
    ]
