# Generated by Django 3.2.16 on 2022-12-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20221210_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['priority', 'id', 'text'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['priority', 'id', 'text'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
    ]
