# Generated by Django 3.2.16 on 2022-12-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20221210_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='passed',
            field=models.DateTimeField(null=True, verbose_name='Дата завершения'),
        ),
    ]
