# Generated by Django 3.2.16 on 2022-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_progress_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один не скрытый/активный вариант ответа', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Виден всем'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один не скрытый/активный вопрос', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Виден всем'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Меняется автоматически при изменении/удалении вопросов и вариантов ответов, если квиз активен и не скрыт', verbose_name='Редакция квиза'),
        ),
    ]
