# Generated by Django 3.2.16 on 2022-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20221220_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-visibility', '-active', 'priority', 'id', 'text'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один вариант ответа', verbose_name='Готов к публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False, help_text='Статус принимает положительное состояние, если есть хотя бы один не скрытый/готовый к публикации вопрос', verbose_name='Готов к публикации'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='empty_answers',
            field=models.BooleanField(default=False, help_text='Только для типов вопросов с несколькими вариантами ответов', verbose_name='Разрешить оставлять выбор пустым'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Меняется автоматически при изменении/удалении вопросов и вариантов ответов, если квиз готов к публикации и не скрыт', verbose_name='Редакция квиза'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='visibility',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
