# Generated by Django 3.2.16 on 2022-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20221222_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='revision',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Меняется автоматически при изменении/удалении вопросов и вариантов ответов, если квиз готов к публикации и не скрыт', verbose_name='Редакция квиза'),
        ),
    ]
