# Generated by Django 3.2.16 on 2022-12-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20221210_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_text',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок квиза'),
        ),
        migrations.AddField(
            model_name='answer',
            name='variant_text',
            field=models.TextField(null=True, verbose_name='Вариант ответа'),
        ),
    ]
