# Generated by Django 3.2.16 on 2022-12-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20221210_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Меняется автоматически при изменении вопросов и вариантов ответов', verbose_name='Номер редакции квиза'),
        ),
    ]
