# Generated by Django 3.2.16 on 2022-12-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_quiz_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Меняется автоматически при изменении/удалении вопросов и вариантов ответов', verbose_name='Редакция квиза'),
        ),
    ]
