# Generated by Django 3.2.16 on 2022-12-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_quiz_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='quiz_revision',
            field=models.PositiveIntegerField(null=True, verbose_name='Редакция квиза'),
        ),
    ]
